# Generated by Django 4.2.4 on 2023-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_companion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
