# Generated by Django 4.2.4 on 2023-12-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_companion', '0006_alter_log_entry_log_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_entry',
            name='log_item',
            field=models.CharField(max_length=30),
        ),
    ]
